stages:
- name: docker-build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lunch:v1
timeout: 60
notification:
  recipients:
  - recipient: '#notofocations'
    notifier: c-dndxg:n-m5qbg
  condition:
  - Success
  - Changed
  - Failed
